In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df =  pd.read_csv("Cleaned_Life_Expectancy.csv")
df

,Unnamed: 0,Country,Year,Status,Life_Expectancy,Adult_Mortality,Infant_Deaths,Alcohol,Percentage_Exp,HepatitisB,...,Tot_Exp,Diphtheria,HIV/AIDS,GDP,Population,thinness_1to19_years,thinness_5to9_years,Income_Comp_Of_Resources,Schooling,winsorized_Life_Expectancy
0,0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1982,2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,...,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2,45.1
1983,2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,...,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5,45.1
1984,2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,...,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0,45.1
1985,2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,...,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8,45.3
1986,2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,...,7.10,78.0,43.5,547.358879,12222251.0,11.0,11.2,0.434,9.8,46.0

In [3]:
df.describe()

,Unnamed: 0,Year,Life_Expectancy,Adult_Mortality,Infant_Deaths,Alcohol,Percentage_Exp,HepatitisB,Measles,BMI,...,Tot_Exp,Diphtheria,HIV/AIDS,GDP,Population,thinness_1to19_years,thinness_5to9_years,Income_Comp_Of_Resources,Schooling,winsorized_Life_Expectancy
count,1987.000000,1987.000000,1987.000000,1987.000000,1987.000000,1987.000000,1987.000000,1987.00000,1987.000000,1987.000000,...,1987.000000,1987.000000,1987.000000,1987.000000,1.987000e+03,1987.000000,1987.000000,1987.000000,1987.000000,1987.000000
mean,1415.366381,2006.984902,67.981782,175.187217,36.623553,4.455644,685.492318,73.86160,2729.561651,36.428636,...,5.902728,80.454454,2.274937,5392.335709,1.358390e+07,5.129995,5.199346,0.603453,11.639054,68.000956
std,833.398098,4.323147,9.706401,131.616942,138.784913,3.976733,1761.669050,29.02807,12102.389143,19.736138,...,2.287467,24.450153,6.005112,11480.810350,6.490113e+07,4.750149,4.844382,0.206026,3.212964,9.656676
min,0.000000,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,2.00000,0.000000,1.400000,...,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000,45.100000
25%,665.000000,2003.000000,61.700000,75.000000,1.000000,0.830000,29.469887,64.00000,0.000000,18.150000,...,4.360000,75.500000,0.100000,384.553107,1.967480e+05,1.600000,1.600000,0.473000,9.700000,61.700000
50%,1447.000000,2007.000000,69.900000,153.000000,4.000000,3.770000,104.314473,86.00000,20.000000,38.700000,...,5.800000,91.000000,0.100000,1334.651896,1.396861e+06,3.300000,3.400000,0.648000,11.900000,69.900000
75%,2061.500000,2011.000000,74.700000,243.000000,25.000000,7.190000,470.870122,95.00000,499.500000,55.000000,...,7.385000,96.000000,1.400000,4441.530655,7.625918e+06,7.600000,7.700000,0.745000,13.700000,74.700000
max,2937.000000,2015.000000,89.000000,723.000000,1800.000000,17.870000,18961.348600,99.00000,212183.000000,77.100000,...,14.390000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.936000,20.700000,89.000000

In [4]:
df.isnull().sum()

Unnamed: 0                    0
Country                       0
Year                          0
Status                        0
Life_Expectancy               0
Adult_Mortality               0
Infant_Deaths                 0
Alcohol                       0
Percentage_Exp                0
HepatitisB                    0
Measles                       0
BMI                           0
Under_Five_Deaths             0
Polio                         0
Tot_Exp                       0
Diphtheria                    0
HIV/AIDS                      0
GDP                           0
Population                    0
thinness_1to19_years          0
thinness_5to9_years           0
Income_Comp_Of_Resources      0
Schooling                     0
winsorized_Life_Expectancy    0
dtype: int64